[package]
name = "miden-core"
version = "0.2.0"
description = "Miden VM core components"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/miden"
categories = ["emulators", "no-std"]
keywords = ["instruction-set", "miden", "program"]
edition = "2021"
rust-version = "1.60"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["math/std", "winter-utils/std", "crypto/std"]

[dependencies]
crypto = { package = "winter-crypto", version = "0.4", default-features = false }
math = { package = "winter-math", version = "0.4", default-features = false }
winter-utils = { package = "winter-utils", version = "0.4", default-features = false }
